import Link from "next/link";

const feed = [
  ['💡','Rahul S.','Can anyone explain TCP vs UDP in simple terms?','Computer Networks','3 answers','+10 XP','/doubts'],
  ['😂','Priya V.','When the professor says “this won’t come in exam” 💀','Meme Room','42 laughs','+25 XP','/memes'],
  ['📚','Arjun K.','Complete Unit 3 Data Structures notes + practice questions','Data Structures','12 saves','+15 XP','/notes'],
  ['🚀','CampusOS','Discover upcoming hackathons, internships and campus opportunities.','Opportunities','8 views','','/opportunities'],
] as const;

export default function Dashboard() {
  return <section className="space-y-6">
    <div className="hero-panel relative overflow-hidden p-6 md:p-9"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-cyan-300/10 blur-3xl"/><p className="eyebrow">LOVELY PROFESSIONAL UNIVERSITY · VERIFIED CAMPUS</p><h1 className="mt-4 text-3xl font-black text-white md:text-5xl">Good morning, Rohit <span className="gradient-text">👋</span></h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Your campus is moving. See what your classmates are learning, what teachers are sharing and where you can jump in.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/doubts" className="hero-cta">Ask a doubt +10 XP</Link><Link href="/notes" className="glass-cta">Share notes</Link></div></div>
    <div className="grid gap-4 sm:grid-cols-3">{[['#12','Campus rank','↑ 4 this week'],['42','Doubts helped','+120 XP'],['12 🔥','Day streak','Keep it alive']].map(([v,l,s])=><div className="glass-card p-5" key={l}><p className="text-2xl font-black text-white">{v}</p><p className="mt-1 text-xs font-bold text-slate-300">{l}</p><p className="mt-2 text-[10px] text-cyan-300">{s}</p></div>)}</div>
    <div className="grid gap-5 lg:grid-cols-[1fr_310px]"><div><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-white">Your campus feed</h2><span className="text-xs text-slate-500">Live · personalised</span></div><div className="space-y-3">{feed.map(([icon,user,content,subject,meta,xp,href])=><Link href={href} key={content} className="glass-card block p-5 transition hover:-translate-y-1 hover:border-cyan-300/20"><div className="flex gap-3"><div className="avatar-orb shrink-0">{icon}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm text-white">{user}</b><span className="tag !px-2 !py-1 !text-[8px]">{subject}</span></div><p className="mt-2 text-sm leading-6 text-slate-300">{content}</p><div className="mt-3 flex justify-between text-[10px] text-slate-500"><span>{meta}</span><span className="text-cyan-300">{xp}</span></div></div></div></Link>)}</div></div><aside className="space-y-3"><div className="glass-card p-5"><p className="eyebrow">CAMPUS PULSE</p><h3 className="mt-3 text-xl font-black text-white">What’s happening</h3><div className="mt-4 space-y-4 text-xs text-slate-400"><p>🟢 <b className="text-white">184</b> students online</p><p>💬 <b className="text-white">27</b> unanswered doubts</p><p>📚 <b className="text-white">9</b> notes shared today</p><p>🎯 <b className="text-white">3</b> opportunities trending</p></div></div><Link href="/leaderboard" className="glass-card block p-5 hover:border-cyan-300/20"><p className="eyebrow">LEADERBOARD</p><p className="mt-3 text-sm font-bold text-white">You are climbing fast ⚡</p><p className="mt-1 text-xs text-slate-500">8 XP to overtake #11</p></Link></aside></div>
  </section>;
}
